version: "3.7"

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        links:
          - mongodb
        restart: always  # container를 실행할 때 항상 이미 수행중이라면 재시작을 수행
        volumes:
            - ./src:/market/src
        ports: # 포트번호 설정
            - 5000:5000
        depends_on: # mongodb시작 후 실행
        - mongodb
    mongodb:
        image: mongo
        restart: always
        ports:
        - 27017:27017
