version: "3.7"

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/myfolder/src
        ports:
            - 5000:5000
        depends_on:
        - mongodb
    mongodb:
        image: mongo
        restart: always
        ports:
        - 9999:9999
